package com.tasly.deepureflow.domain.system;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "Place")
public class Place {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_area.AreaCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_area.AreaName
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_area.ParentAreaCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    private String parentareacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_area.ProvinceCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    private String provincecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_area.Attr1
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    private String attr1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_area.AreaCode
     *
     * @return the value of org_area.AreaCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_area.AreaCode
     *
     * @param areacode the value for org_area.AreaCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_area.AreaName
     *
     * @return the value of org_area.AreaName
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_area.AreaName
     *
     * @param areaname the value for org_area.AreaName
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_area.ParentAreaCode
     *
     * @return the value of org_area.ParentAreaCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public String getParentareacode() {
        return parentareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_area.ParentAreaCode
     *
     * @param parentareacode the value for org_area.ParentAreaCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public void setParentareacode(String parentareacode) {
        this.parentareacode = parentareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_area.ProvinceCode
     *
     * @return the value of org_area.ProvinceCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public String getProvincecode() {
        return provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_area.ProvinceCode
     *
     * @param provincecode the value for org_area.ProvinceCode
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public void setProvincecode(String provincecode) {
        this.provincecode = provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_area.Attr1
     *
     * @return the value of org_area.Attr1
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_area.Attr1
     *
     * @param attr1 the value for org_area.Attr1
     *
     * @mbggenerated Wed Sep 16 10:41:11 CST 2015
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }
}